env: "local"

http_server:
  host: "host.docker.internal"
  port: 8082
  timeout: 4s
  idle_timeout: 30s
  shutdown_timeout: 5s
  read_timeout: 5s
  write_timeout: 10s
  read_header_timeout: 2s
  max_header_bytes: 1048576

swagger_server:
  json_path: "/app/swagger.json" # путь внутри контейнера
  ui_path: "/app/swaggerui" # путь внутри контейнера

postgres:
  host: "host.docker.internal"
  port: 5432
  user: "postgres"
  password: "secret"
  dbname: "subscriptions_test"
  sslmode: "disable"

  migrations_path: "/app/migrations"   # путь внутри контейнера
  migrations_table: "test_migrations"

  retry:
    attempts: 10
    initial_delay: 1s
    max_delay: 10s
    step: 2s
